### ISSUE TITLE
Update Vagrant image to 1709

### ISSUE THREAD

**Issue by teonivalois** [StefanScherer/packer-windows#101]
Upgrade the vagrant image "StefanScherer/windows_2016_docker" to Windows Server 1709.

**Comment by StefanScherer** [comment]
Thanks for the suggestion. But I can't provide Server 1709 images in Vagrant Cloud. There is no Evaluation ISO for 1709. Hopefully the next LTSC Server 2019 later this year...

**Comment by teonivalois** [comment]
Not as an ISO, but you could apply the update using [Powershell](https://www.tenforums.com/tutorials/76207-update-upgrade-windows-10-using-powershell.html). I just applied it to one VM of windows_2016_docker that I have here...

**Comment by StefanScherer** [comment]
I don‘t think you receive the Server 1709 this way. The packer build runs a similar update script and the box is available in Vagrant Cloud. But this usn‘t a Server 1709, it‘s still Server 2016 with latest updates.

**Comment by StefanScherer** [comment]
Closing this. The windows_2016_docker image contains the 2016 LTS version.
