### ISSUE TITLE
WinRM timing out

### ISSUE THREAD

**Issue by dfranciscus** [StefanScherer/packer-windows#107]
For some reason having an issue connecting with WinRM. I have changed the credentials to a different account, but I think that is all I have done differently on my repo. Any insight would be appreciated.

2018/06/22 10:45:06 packer.exe: 2018/06/22 10:45:06 [INFO] Attempting WinRM connection...
2018/06/22 10:45:06 packer.exe: 2018/06/22 10:45:06 [DEBUG] connecting to remote shell using WinRM
2018/06/22 10:46:25 packer.exe: 2018/06/22 10:46:25 [ERROR] connection error: unknown error Post http://127.0.0.1:3667/wsman: read tcp 12
7.0.0.1:52507->127.0.0.1:3667: wsarecv: An existing connection was forcibly closed by the remote host.
2018/06/22 10:46:25 packer.exe: 2018/06/22 10:46:25 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:3667/wsman: read tc
p 127.0.0.1:52507->127.0.0.1:3667: wsarecv: An existing connection was forcibly closed by the remote host.
2018/06/22 10:46:30 packer.exe: 2018/06/22 10:46:30 [INFO] Attempting WinRM connection...
2018/06/22 10:46:30 packer.exe: 2018/06/22 10:46:30 [DEBUG] connecting to remote shell using WinRM
2018/06/22 10:47:47 packer.exe: 2018/06/22 10:47:47 [ERROR] connection error: unknown error Post http://127.0.0.1:3667/wsman: read tcp 12
7.0.0.1:52523->127.0.0.1:3667: wsarecv: An existing connection was forcibly closed by the remote host.
2018/06/22 10:47:47 packer.exe: 2018/06/22 10:47:47 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:3667/wsman: read tc
p 127.0.0.1:52523->127.0.0.1:3667: wsarecv: An existing connection was forcibly closed by the remote host.
2018/06/22 10:47:52 packer.exe: 2018/06/22 10:47:52 [INFO] Attempting WinRM connection...
2018/06/22 10:47:52 packer.exe: 2018/06/22 10:47:52 [DEBUG] connecting to remote shell using WinRM
2018/06/22 10:48:36 packer.exe: 2018/06/22 10:48:36 [ERROR] connection error: http response error: 401 - invalid content type
2018/06/22 10:48:36 packer.exe: 2018/06/22 10:48:36 [ERROR] WinRM connection err: http response error: 401 - invalid content type
2018/06/22 10:48:41 packer.exe: 2018/06/22 10:48:41 [INFO] Attempting WinRM connection...
2018/06/22 10:48:41 packer.exe: 2018/06/22 10:48:41 [DEBUG] connecting to remote shell using WinRM
2018/06/22 10:48:41 packer.exe: 2018/06/22 10:48:41 [ERROR] connection error: http response error: 401 - invalid content type
2018/06/22 10:48:41 packer.exe: 2018/06/22 10:48:41 [ERROR] WinRM connection err: http response error: 401 - invalid content type
2018/06/22 10:48:46 packer.exe: 2018/06/22 10:48:46 [INFO] Attempting WinRM connection...
2018/06/22 10:48:46 packer.exe: 2018/06/22 10:48:46 [DEBUG] connecting to remote shell using WinRM
2018/06/22 10:48:46 packer.exe: 2018/06/22 10:48:46 [ERROR] connection error: http response error: 401 - invalid content type
2018/06/22 10:48:46 packer.exe: 2018/06/22 10:48:46 [ERROR] WinRM connection err: http response error: 401 - invalid content type
2018/06/22 10:48:51 packer.exe: 2018/06/22 10:48:51 [INFO] Attempting WinRM connection...
2018/06/22 10:48:51 packer.exe: 2018/06/22 10:48:51 [DEBUG] connecting to remote shell using WinRM

**Comment by StefanScherer** [comment]
I never tried it with different values, but have you changed both
- the packer template https://github.com/StefanScherer/packer-windows/blob/34bfd35bfdd5ab16dcb77de5dea6bb0ac68cecaf/windows_2016.json#L67-L69
- the Autounattend.xml https://github.com/StefanScherer/packer-windows/blob/34bfd35bfdd5ab16dcb77de5dea6bb0ac68cecaf/answer_files/2016/Autounattend.xml#L222-L237

In the packer json, watch out that you change for the correct builder. There are up to three builder sections in the json file.

**Comment by dfranciscus** [comment]
So I think the issue is that win-updates.ps1 just sits there and nothing is happening and eventually WinRM times out. I will investigate further.

**Comment by StefanScherer** [comment]
You can check the logfile at `C:\Windows\Temp\win-updates.log` of win-updates.ps1 script. This always has been the most flaky part of the packer build.
The current templates worked fine today, I've updated my Vagrant boxes today. Here is one of the build jobs https://circleci.com/gh/StefanScherer/packer-builder/215 and the boxes are uploaded to app.vagrantup.com.

**Comment by dfranciscus** [comment]
Yeah I have the most current I believe. So it looks like the first pass of update works fine, it installs them. After a reboot that is when it just sits. Nothing much is showing in the log that looks like a problem. Very odd.

**Comment by dfranciscus** [comment]
So it appears if you use mistakenly swap the username and password for WinRM  credentials, Packer cant connect. :) I am dumb. Closing.

**Comment by StefanScherer** [comment]
Now I know why we all use `vagrant` and `vagrant` :-)
