### ISSUE TITLE
debloat.zip fails to download

### ISSUE THREAD

**Issue by chaospixel** [StefanScherer/packer-windows#114]
I ran `packer build --only virtualbox-iso .\windows_10.json`

While the build succeeds, there are errors reported in the log output...

Log output
```
==> virtualbox-iso: Provisioning with powershell script: ./scripts/debloat-windows.ps1
    virtualbox-iso: Downloading debloat zip
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure virtualbox-iso: channel."

```

**Comment by StefanScherer** [comment]
Thanks. This is normally a problem with missing TLS 1.2 default in PowerShell. Could you try the fix in #115 ?
