### ISSUE TITLE
Seems a bit odd to group screensaver disabling with windows update for Windows 10.

### ISSUE THREAD

**Issue by nelsonjchen** [StefanScherer/packer-windows#121]
https://github.com/StefanScherer/packer-windows/blob/bc4e6442baa2f8a8cc367d7e5412cb5fdd6e3c82/answer_files/10/Autounattend.xml#L217-L222

I am starting to base my builds on the Windows 10 `Autounattend.xml` in this repo and I couldn't help but wonder why screen saver disabling was grouped in with enabling/disabling Windows updates. It should probably be moved to the general area.

**Comment by StefanScherer** [comment]
You can send a pull request if you have a better idea. Pull requests are really welcome :-)
