### ISSUE TITLE
Windows update boot loop with windows_10 template

### ISSUE THREAD

**Issue by StefanScherer** [StefanScherer/packer-windows#125]
The latest cumulative update 2018-09 on Windows 10 seems to make a problem with the current win-updates.ps1 script.

The win-updates.ps1 script runs into a boot loop.

<img width="882" alt="bildschirmfoto 2018-09-13 um 07 24 53" src="https://user-images.githubusercontent.com/207759/45468822-fad98600-b726-11e8-98d3-0ea1fc00f750.png">

I had to manually stop the win-updates.ps1 script and open the "Check for updates" dialog and install the update from there. After the reboot the win-updates.ps1 script found out that it should finish and opens WinRM port.

<img width="882" alt="bildschirmfoto 2018-09-13 um 07 25 27" src="https://user-images.githubusercontent.com/207759/45468847-2492ad00-b727-11e8-9754-2c7332c1ebd6.png">

The win-updates.ps1 and the closed WinRM port until all updates are finished are the pain point of this packer templates. Once again I think of moving to another way to install the updates.
- https://github.com/rgl/packer-provisioner-windows-update (disadvantage: You have to install a packer plugin manually in your host environment)
- https://github.com/windowsbox/powershellmodules
But I don't know if that really helps.

**Comment by lnxg33k** [comment]
@StefanScherer Somehow it worked for me, I had to set the winrm timeout forever tho.

**Comment by lnxg33k** [comment]
Yeah I am facing this issue right now, but tbh I don't see installing provisioner-windows-update plugin as a disadvantage if it is going to solve this issue.

**Comment by StefanScherer** [comment]
Fixed with #132 using the latest Windows 10 1809 eval ISO.
