### ISSUE TITLE
`post_shutdown_delay` not found

### ISSUE THREAD

**Issue by toddpi314** [StefanScherer/packer-windows#130]
OS: `Debian GNU/Linux 9 (stretch)`
Packer: `0.10.2`
Command: `packer build --only=virtualbox-iso windows_2016_docker.json`

Removing the `post_shutdown_delay` in `windows_2016_docker.json` worked just fine.

**Comment by StefanScherer** [comment]
Oh, Packer 0.10 is no longer supported with my templates. There is Packer 1.3.1. Please try to update your Packer.
