### ISSUE TITLE
Windows 10 answer file does not work

### ISSUE THREAD

**Issue by fnbr** [StefanScherer/packer-windows#143]
I tried building windows 10 with virtual box and have issues with the answer files:
The ProductKey cannot be read. I looks the xml has the wrong format and the key itself is missing a part.
If I enter a different key, I then get stuck first and the select language screen and after that on a screen saying "no images available".

Any ideas what went wrong?

**Comment by StefanScherer** [comment]
Which ISO filedo you use?

**Comment by fnbr** [comment]
The one from here: https://www.microsoft.com/de-de/software-download/windows10ISO

**Comment by fnbr** [comment]
The ProductKey usually consists of 5 parts, the one in the Windows 10 answer file only consists of four. It also not enclosed in <Key></Key>

**Comment by StefanScherer** [comment]
https://github.com/StefanScherer/packer-windows#product-keys mentions the trial ISO's.
Can I encourage you to make this section more clean in a pull request? :-)
