### ISSUE TITLE
Windows 10 1809 virtualbox hangs

### ISSUE THREAD

**Issue by git14** [StefanScherer/packer-windows#145]
When running `vagrant up` it times out on `default: WinRM transport: negotiate`.
The vm does boot in virtaulbox, but there are no network devices present.
Used `packer build --only=virtualbox-iso .\windows_10.json` to build the box.

**Comment by git14** [comment]
Same result when using https://app.vagrantup.com/StefanScherer/boxes/windows_10

**Comment by basictheprogram** [comment]
> On Nov 30, 2018, at 12:30 PM, git14 <notifications@github.com> wrote:
> 
> When running vagrant up it times out on default: WinRM transport: negotiate.
> The vm does boot in virtaulbox, but there are no network devices present.
> Used packer build --only=virtualbox-iso .\windows_10.json to build the box.
> 

Something happening like this: https://github.com/chocolatey/chocolatey-test-environment/issues/31

Which looks to be related to this: https://www.virtualbox.org/ticket/18152

Which might have something to do with this: https://github.com/chocolatey/chocolatey-test-environment/issues/32

---
Bob Tanner <tanner@real-time.com>           | Phone : 952-943-8700
http://www.real-time.com, Linux, macOS      | Fax   : 952-943-8500
Key fingerprint = F785 DDFC CF94 7CE8 AA87 3A9D 3895 26F1 0DDB E378

**Comment by git14** [comment]
Tried ```config.vm.provider "virtualbox" do |v|
  v.default_nic_type = "82543GC"
end```
No change.

**Comment by basictheprogram** [comment]
I think the problem is with vagrant.

If I go import the .box directly into VirtualBox things work as expected.

**Comment by git14** [comment]
Confirmed it's a Vagrant with virtualbox issue. I was running Vagrant 2.2.1. Upgraded to 2.2.2, now I get the warning but the vm loads with networking. Oddly enough when I add in the default nic type into the config it breaks networking.
