### ISSUE TITLE
differencing_disk depracated

### ISSUE THREAD

**Issue by Jvekka** [StefanScherer/packer-windows#168]
Hyper-V configuration differencing_disk has been depracated and replaced with linked_clone in Vagrant.
Are you already changing templates or should I create (my 1st) PR about it?

config.vm.provider "hyperv" do |v|
        v.cpus = 2
        v.maxmemory = 2048
        **v.differencing_disk = true**
    end

**Comment by StefanScherer** [comment]
Please @Jvekka send me a PR for that!

**Comment by Jvekka** [comment]
Created pull request to your "my" branch with corrected configuration for Vagrant/Hyper-V.
#169

**Comment by StefanScherer** [comment]
Fixed with #169.
Thanks again!
