### ISSUE TITLE
Document screen resolution settings

### ISSUE THREAD

**Issue by Gerromie** [StefanScherer/packer-windows#173]
The README says that full screen support is added for MacBook retina displays. Could you please document the method to get (at least the Vagrant box StefanScherer/windows_2019_docker) to a resolution greater than the default (which is perhaps 640x480)?

**Comment by StefanScherer** [comment]
Good point. I normally use this https://github.com/StefanScherer/windows-docker-desktop-box/blob/aa9c3527dcb227014073317bf3a49a836283eb28/Vagrantfile#L43-L51

```ruby
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
    v.vmx["mks.enable3d"] = "TRUE"
    v.vmx["mks.forceDiscreteGPU"] = "TRUE"
    v.vmx["gui.fullscreenatpoweron"] = "TRUE"
    v.vmx["gui.viewmodeatpoweron"] = "fullscreen"
    v.vmx["gui.lastPoweredViewMode"] = "fullscreen"
    v.enable_vmrun_ip_lookup = false
  end
```

It starts the VM in full screen and enables retina resolution. The Vagrant box itself then boots, but you have to logout once to have the HiDPI enabled inside the Windows VM. Afterwards halting and booting the VM always works in HiDPI mode.

**Comment by StefanScherer** [comment]
The StefanScherer/windows_2019_docker is a Windows Server core, you can do the same here for HiDPI, but you won't have much experience as there only is the cmd.exe shell and notepad.exe. :-)

**Comment by Gerromie** [comment]
Thank you. I will try that out. I'd just like a window size that's a bit bigger than 640x480 (not necessarily full screen), but I hadn't found the right settings, yet.
