### ISSUE TITLE
debloat-windows.ps1 downloading a zip of scripts?

### ISSUE THREAD

**Issue by Joeasaurus** [StefanScherer/packer-windows#18]
Why are you obfuscating the debloat step by having it download a zip of scripts? Can you not just store the scripts next to the debloat script, in the folder called "scripts"?

**Comment by Joeasaurus** [comment]
Ooooh I see it's because they're in a different repository. Interesting.

**Comment by StefanScherer** [comment]
Yes :-) I've seen that second repo and liked the idea. But I have to remove a lot of this again as I cannot build a domain controller with the windows_2016_docker basebox, seems I have stopped too many services etc. It's not easy to have a usable, but still battery aware image.
