### ISSUE TITLE
Windows Server vagrant box defaults to data center edition

### ISSUE THREAD

**Issue by mountaindude** [StefanScherer/packer-windows#184]
As per the main readme: "All Windows Server versions are defaulted to the Server Standard edition".

But when I use v2019.04.11 (currently latest) to create a new VM using Vagrant (https://app.vagrantup.com/StefanScherer/boxes/windows_2019) I get a VM that tells me it's "Windows Server 2019 Datacenter Evaluation".

Is there an easy way (not involving setting up the build stack for boxes) to make the VM be standard edition instead?

**Comment by StefanScherer** [comment]
Beginning with 1709, 1809, 2019 we switched to Datacenter Eval.
If you want to change it you have to adjust the `Autounattend.xml` and run a new `packer build`.

```
answer_files/2019/Autounattend.xml:                            <Value>Windows Server 2019 SERVERDATACENTER</Value>
answer_files/2019_core/Autounattend.xml:                            <Value>Windows Server 2019 SERVERDATACENTERCORE</Value>
answer_files/server_1709/Autounattend.xml:                            <Value>Windows Server 2016 SERVERDATACENTERACORE</Value>
answer_files/server_1803/Autounattend.xml:                            <Value>Windows Server 2016 SERVERDATACENTERACORE</Value>
answer_files/server_insider/Autounattend.xml:                            <Value>Windows Server 2019 SERVERDATACENTERACORE</Value>
answer_files/server_insider_uefi/Autounattend.xml:                            <Value>Windows Server 2016 SERVERDATACENTERACORE</Value>
```
