### ISSUE TITLE
app.vagrantup.com does not contain HyperV providers

### ISSUE THREAD

**Issue by bryansoto** [StefanScherer/packer-windows#190]
Sorry if this isn't an appropriate place for this. I couldn't think of any other.

The HyperV provider no longer appears to be created or uploaded to app.vagrantup.com.

As an example: https://app.vagrantup.com/StefanScherer/boxes/windows_2019

Version 2019.05.15 has providers only for VirtualBox and VMWare_Desktop. 
Version 2019.04.11 has providers for VirtualBox, VMWare_Desktop *and* HyperV.

StefanScherer/windows_10 is the same with HyperV available with version 2019.04.11.

StefanScherer/windows_2019_docker lost HyperV with version 2019.03.17.

**Comment by StefanScherer** [comment]
@bryansoto thanks for the feedback. Yes, the latest builds for Hyper-V have a problem https://circleci.com/gh/StefanScherer/packer-builder/721 and I didn't have time to repair the build process.

**Comment by bryansoto** [comment]
Ah, I was hoping I could help out, but unfortunately the root of the problem seems to lie with Azure permissions when creating the VM via Terraform. Specifically with HDInsight.

```
* provider.azurerm: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.HDInsight with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'c36e7700-8a9a-4ce2-8eaf-22bca1f5f837' with object id 'c36e7700-8a9a-4ce2-8eaf-22bca1f5f837' does not have authorization to perform action 'Microsoft.HDInsight/register/action' over scope....".
```

Thank you for doing the work to provide these to the world. It is useful and appreciated. :)

**Comment by StefanScherer** [comment]
New boxes are currently uploading. I manually kicked the packer build as there are two problems.

The first problem is that terraform azure provider needs more permissions. Will investigate and file an issue ans I do not use the HDInsight here. Workaround is to pin an older version of the provider.

Another problem is that the packer build script is killed immediatelly through the Windows OpenSSH connection. Have to look for another way as "nohup" doesn't seem to work as it did earlier.
