### ISSUE TITLE
Cannot activate Windows 10 image

### ISSUE THREAD

**Issue by fasmat** [StefanScherer/packer-windows#191]
Hi Stefan,

I downloaded your Windows 10 box yesterday and it works perfectly for me in VMWare on macOS. Thanks for your work!

I now want to use the Windows productively but my activation continues to fail. I always get the error message: The product key you entered didn't work. Check the product key and try again or enter a different one. (0xc004f050)

The key is from my MSDN subscription and should work on a Windows 10 Enterprise system. When I googled for this error I didn't find any solution that worked for me.

Can you help?

Thanks,
Matthias

**Comment by StefanScherer** [comment]
Hi Matthias,

Thanks. These boxes are based on the Enterprise Eval ISO's and cannot be activated with a license.
You have to build your own.
1. Download the Windows 10 ISO from MSDN
2. Adjust or create an own answer file based on `answer_files/10/Autounattend.xml` and adjust it
    - adjust the `Windows 10 Enterprise Evaluation` to eg. `Windows 10 Enterprise`
    - enter the product key (or leave it out of the xml file, then activate it manually later)
3. Run a packer build, see lines 1-6 in https://github.com/StefanScherer/packer-windows/blob/my/build_windows_10.ps1#L1-L6 as an example how to customize the packer build.

**Comment by fasmat** [comment]
Hi Stefan,

thank you for the quick answer. I see, then I'll build my own boxes. Thanks!
