### ISSUE TITLE
Unable to RDP into StefanScherer/windows_2019

### ISSUE THREAD

**Issue by rabrahamOpti** [StefanScherer/packer-windows#208]
After provisioning the box with `vagrant up`, I attempted `vagrant rdp` and saw the following windows error message:

![RemoteDesktopConnectionErrorWindow](https://user-images.githubusercontent.com/28309959/65280051-85ed1900-dafd-11e9-9f57-115aaeb8f57f.PNG)

Here's the related vagrant output:
```
$ vagrant up
Bringing machine 'default' up with 'vmware_workstation' provider...
==> default: Box 'StefanScherer/windows_2019' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'StefanScherer/windows_2019'
    default: URL: https://vagrantcloud.com/StefanScherer/windows_2019
==> default: Adding box 'StefanScherer/windows_2019' (v2019.09.12) for provider: vmware_desktop
    default: Downloading: https://vagrantcloud.com/StefanScherer/boxes/windows_2019/versions/2019.09.12/providers/vmware_desktop.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    default:
==> default: Successfully added box 'StefanScherer/windows_2019' (v2019.09.12) for 'vmware_desktop'!
==> default: Cloning VMware VM: 'StefanScherer/windows_2019'. This can take some time...
==> default: Checking if box 'StefanScherer/windows_2019' version '2019.09.12' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 3389 => 3389
    default: -- 35729 => 35729
    default: -- 5985 => 5985
    default: -- 1433 => 1433
    default: -- 5986 => 55986
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:5985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Configuring network adapters within the VM...
==> default: Configuring secondary network adapters through VMware
==> default: on Windows is not yet supported. You will need to manually
==> default: configure the network adapter.
==> default: Enabling and configuring shared folders...
    default: -- C:/dev/DevOps/StefanScherer_Windows_2019: /vagrant
```

```
$ vagrant rdp
==> default: Detecting RDP info...
    default: Address: 127.0.0.1:3389
    default: Username: vagrant
==> default: Vagrant will now launch your RDP client with the connection parameters
==> default: above. If the connection fails, verify that the information above is
==> default: correct. Additionally, make sure the RDP server is configured and
==> default: running in the guest machine (it is disabled by default on Windows).
==> default: Also, verify that the firewall is open to allow RDP connections.
```

```
$ vagrant box list
StefanScherer/windows_2016 (vmware_desktop, 2019.02.14)
StefanScherer/windows_2019 (vmware_desktop, 2019.09.12)
```

```
$ vagrant -v
Vagrant 2.2.5
```

VMWare Workstation Version: 15.1.0 build-13591040

**Comment by rabrahamOpti** [comment]
I updated the original post with my vagrant version (2.2.5) and my VMWare Workstation Version (15.1.0 build-13591040)

**Comment by rabrahamOpti** [comment]
It looks like I'm also having issues with a `StefanScherer/windows_2016` box I definitely was able to use in the past. I've just upgraded to the latest vagrant and vmware workstation, so this may be an issue with that, rather than this box. If I verify that, I'll update this issue for anyone else that hits this problem, and close the issue.

**Comment by rabrahamOpti** [comment]
Installing the latest windows updates on my base machine resolved the issue. Thank you for rubber ducking :)

**Comment by johnatank** [comment]
For anyone who may encounter similar error.
It appers RTP service is not bringing up 3389 port if "Don't allow remote connections" is set at machine where `vagrant up` is called. Since port is not up, vagrant is not changing port due to collusion and create port forwarding rule from host:3389 to guest:3389 as default Vagrantfile has below config:
```
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct:true
```
So VM provider opens port 3389 at 0.0.0.0:
```
 TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING
 [vmnat.exe]
```
But somehow, Windows is still accepting connections to localhost/machine IP via mstsc.exe at default RDP port 3389 and responding with error reported here. Same error will happen even when vagrant box is not running too. 

Having the same behavior on two different laptops with Windows 10 and Windows 11. 

Configuring custom host port to override default port worked:
```
  config.vm.network :forwarded_port, guest: 3389, host: 33890, id: "rdp", auto_correct:true
```
Also, enabling RDP connections on machine, where `vagrant up` is called, helped too because RDP service starts listening to 3389 port which makes vagrant to auto correct port as `auto_correct` is true.
