### ISSUE TITLE
[Hyper-v] Fail to import machine

### ISSUE THREAD

**Issue by jacquecosta** [StefanScherer/packer-windows#209]
Hi,

I am tryng to `vagrant up` this [Windows 10 box](https://app.vagrantup.com/StefanScherer/boxes/windows_10/versions/2019.09.12), but when hyperv will create the register, vagrant is returning:

> ==> hyperv: Successfully added box 'StefanScherer/windows_10' (v2019.09.12) for 'hyperv'!
> ==> hyperv: Importing a Hyper-V instance
>     hyperv: Creating and registering the VM...
> An error occurred while executing a PowerShell script. This error
> is shown below. Please read the error message and see if this is
> a configuration error with your system. If it is not, then please
> report a bug.
> 
> Script: import_vm.ps1
> Error:
> 
> Falha ao importar uma mÃ¡quina virtual.
> 
> Error Code: 32784
> Cause: VM version is unsupported

Running  `Get-VMHostSupportedVersion -Default` the version is 8.0 and Windows server 2016 Datacenter (Anniversary)

Is any way to deal with that?

**Comment by StefanScherer** [comment]
@jacquecosta Good question. I haven't used the hyperv boxes for a while, I normally run the vmware and sometimes the virtualbox versions.
The hyperv boxes are built on a Windows Server 2019, maybe this sets a higher version. 🤔 

Have you tried the hyperv box from https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1909-enterprise ?

Ah, looking through the packer docs I found this: https://packer.io/docs/builders/hyperv-iso.html#configuration_version

OK, the version table https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/upgrade-virtual-machine-version-in-hyper-v-on-windows-or-windows-server#supported-vm-configuration-versions-for-long-term-servicing-hosts shows me that we should add version "8.0" to the packer templates to have them compatible for more people in the community.

**Comment by StefanScherer** [comment]
PR #211 might help to make fresh boxes work with Windows Server 2016.
I can create new hyperv boxes and publish them soon.

**Comment by jacquecosta** [comment]
@StefanScherer Nice, I will be waiting for it!

About this [box](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1909-enterprise) in his description is: "Hyper-V Generation 1, Configuration Version 9.0 (requires Windows 10 version 1809 or Windows Server 2019 host)", so doesn't run in my context.

**Comment by StefanScherer** [comment]
@jacquecosta I've uploaded a new [windows_10](https://app.vagrantup.com/StefanScherer/boxes/windows_10/versions/2019.09.26) hyperv box, please have give it a try.

**Comment by jacquecosta** [comment]
@StefanScherer This one now is getting up, but I needed to change rules configs [wasn't pingging the VM](https://social.technet.microsoft.com/Forums/en-US/2a92bc04-1ee3-48c9-9940-7d47ccbb2157/hyperv-i-cant-sucessfully-ping-vms-the-ping-timesout?forum=winserverhyperv) to vagrant connect/identify the machine.

**Comment by jacquecosta** [comment]
Well, just for knowledge, I followed this [steps](https://www.thomasmaurer.ch/2017/07/how-to-setup-nested-virtualization-in-microsoft-azure/) and now everything is working :) 
thanks!

**Comment by StefanScherer** [comment]
Thanks for the detail how to setup the hyperv host.

In the meantime I also released the windows_2019 and windows_2019_docker boxes with the VM version 8.0. 

I think this issue is fixed now.
