### ISSUE TITLE
Error getting WinRM host: IP lookup failed

### ISSUE THREAD

**Issue by rabrahamOpti** [StefanScherer/packer-windows#218]
I'm trying to use the packer templates in this repo to create a vagrant box for VMWare workstation that runs a Windows Server 2019 Datacenter (Desktop Experience) image

My packer build command hangs at the following line: `vmware-iso: Waiting for WinRM to become available...`

I'm using `packer-windows-2019.10.09/answer_files/2019_core/Autounattend.xml`

Changes I've made to that file:

- `<Value>Windows Server 2019 Datacenter (Desktop Experience)</Value>`
- Commented out the < !-- WITH WINDOWS UPDATES --> section, and commented in the < !-- WITHOUT WINDOWS UPDATES --> section
- Added my MAK key in UserData/ProductKey/Key

I'm also using `packer-windows-2019.10.09/windows_2019_core.json`
 
Changes I've made to that file:

- Updated the iso_url to refer to the iso I've downloaded into the iso folder
- Updated the iso_checksum to that of the iso I've downloaded
- I removed the builders for hyperv and virtualbox
- After running into this issue, I added "winrm_port": "55985" per a suggestion in this article: http://www.hurryupandwait.io/blog/creating-windows-base-images-for-virtualbox-and-hyper-v-using-packer-boxstarter-and-vagrant. It didn't help.

On my local machine, I made my network's profile private, and ran `Winrm quickconfig` to get the Windows Remote Management service running on my machine

I ran packer with `packer build windows_2019_core.json`

I set environment variables to have packer output debug logs per these instructions: https://www.packer.io/docs/other/debugging.html

In those logs, I noticed the following lines being repeated over and over again (which is where it's hung)

```
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 Searching for file 'C:/ProgramData/VMware/netmap.conf'
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 Found file 'C:/ProgramData/VMware/netmap.conf'
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 Located networkmapper configuration file using Workstation: C:/ProgramData/VMware/netmap.conf
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 GuestIP discovered device matching nat: vmnet8
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 Lookup up IP information...
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 GuestAddress found MAC address in VMX: **:**:**:**:**:**
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 Trying DHCP leases path: C:/ProgramData/VMware/vmnetdhcp.leases
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC **:**:**:**:**:**
2019/10/22 15:38:58 packer.exe: 2019/10/22 15:38:58 [DEBUG] Error getting WinRM host: IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC **:**:**:**:**:**
```

Is there a configuration step I missed? Have I misconfigured something in my environment?

**Comment by StefanScherer** [comment]
I haven't used Windows host for a long time, but when I remember back I didn't customize it. I just installed VMware Workstation and packer and that's all you need.
You don't need the WinRM service on the host, packer will use WinRM protocol to talk to the VM. Inside the VM WinRM will be enabled at some point.
You can leave the hyperv and virtualbox sections in the json, just use `packer build --only vmware-iso ...` to skip other builders.
Other than that, I don't know what causes your issue.
