### ISSUE TITLE
Fix packing Windows 7

### ISSUE THREAD

**Issue by MShekow** [StefanScherer/packer-windows#224]
Hi,

because `windows_7.json` lacks the `enable-winrm.ps1` in the `floppy` entries, an error is caused in `win-updates.ps1:129` once all Windows updates have been installed. The creation of the box just grinds to a halt.

Best regards!

**Comment by StefanScherer** [comment]
I don't actively maintain the `windows_7.json`. If you have a fix for it, please send a PR to share it with the community.
