### ISSUE TITLE
Vagrant windows_2019 version 2019.11.15 virtualbox image is 1809, not 1903

### ISSUE THREAD

**Issue by muddman** [StefanScherer/packer-windows#229]
https://app.vagrantup.com/StefanScherer/boxes/windows_2019/versions/2019.11.15

Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2019.11.15"
end

The virtualbox image is coming up as Windows Server 2019 Version 1809 (OS Build 17763.864) -- isn't it supposed to be 1903?

thanks!!

p

**Comment by StefanScherer** [comment]
Hi @muddman, the `windows_2019` box in Vagrant Cloud is always the LTSC version, so no update to Windows  Server 1903 SAC. This box is based on the Enterprise Eval ISO available and there is only one for Server 2019, not for the semi-annual releases.
You would have to build your own with an ISO file from MSDN account and run

```
packer build --only virtualbox -var iso_url=path-to-server-1903.iso windows_server_1903.json
```

**Comment by muddman** [comment]
thanks and thanks for providing these!
