### ISSUE TITLE
Feature: Add "Replace a Process Level Token" to vagrant

### ISSUE THREAD

**Issue by pryorda** [StefanScherer/packer-windows#237]
Can we add the "Replace a Process Level Token" to vagrant user? This will allow us to switch users during chef provisioning and powershell scripts.

**Comment by StefanScherer** [comment]
Hi @pryorda, well if that helps using chef, and doesn't disturb other usage, I'm fine with it.
If you want, you can create a pull request.

**Comment by pryorda** [comment]
I'll try to get familiar with your configuration s and add it
