### ISSUE TITLE
VirtualBox 6.1 renamed --clipboard to --clipboard-mode

### ISSUE THREAD

**Issue by aucampia** [StefanScherer/packer-windows#240]
There is no more `--clipboard` in VirtualBox 6.1 - it is now `--clipboard-mode`:

https://www.virtualbox.org/manual/UserManual.html#vboxmanage-cmd-overview

This causes the following to fail: https://github.com/StefanScherer/packer-windows/blob/2020.01.15/vagrantfile-windows_10.template#L25

With this error:

```
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "cb2b1fff-eaa6-45a6-8007-c5b488865b1f", "--clipboard", "bidirectional"]
```

Just a heads up - I guess since VirtualBox 6.1 is not supported yet by vagrant this can technically not be considered a bug yet.

**Comment by StefanScherer** [comment]
Thank you. I’ll take a look when vagrant supports it and adjust the templates.
What‘s your experience? No other issues?

**Comment by alysov** [comment]
The [latest version of vagrant, 2.2.7, supports virtualbox 6.1.x](https://github.com/hashicorp/vagrant/blob/v2.2.7/CHANGELOG.md).  Looking forward to removing the [temporary fix](https://github.com/hashicorp/vagrant/issues/11288#issuecomment-571231282).  😉

**Comment by StefanScherer** [comment]
Thanks @alysov I'll take a look soon.

**Comment by alexhaydock** [comment]
I am having this issue also on macOS, but I can't help but wonder what will happen if the templates are updated to use the new `--clipboard-mode` flag. Surely this will just cause everything to break in the same way for users still on VirtualBox <6.1? Seems like that could affect a lot of LTS Linux distro users.

**Comment by basictheprogram** [comment]
https://github.com/hashicorp/vagrant/issues/11288#issuecomment-571231282

**Comment by StefanScherer** [comment]
I've created #242 to rename the parameter.
Sooner or later users update their VirtualBox, so I'm fine with that change.
