### ISSUE TITLE
Cleanup winRM

### ISSUE THREAD

**Issue by ghost** [StefanScherer/packer-windows#249]
Hey Stefan,

Can you help me to understand how can I use winRM cleanup script in my packer manifest. I have a requirement to run both sysprep and winRM cleanup before packer completes the windows build. It seems like they both can't be achieved  by packer because when I run sysprep and reboot the VM first, packer doesn't recognize its winRM connection and ends up failing that it earlier connection was closed forcefully . If I run winRM cleanup first and I can't run any commands since packer uses winRM .

**Comment by StefanScherer** [comment]
Hm, I don't have an idea for that.
