### ISSUE TITLE
[Question] Can this project be used to create Azure VM OS Images?

### ISSUE THREAD

**Issue by boldandbusted** [StefanScherer/packer-windows#251]
Thanks in advance! :)

**Comment by StefanScherer** [comment]
Good question :-)
There is one packer template used to create an Azure VM image. https://github.com/StefanScherer/packer-windows/blob/my/windows_2019_docker_azure.json
There are a few scripts that prepare the VM to be usable in Azure.

I did this setup some time ago http://stefanscherer.github.io/terraforming-a-windows-insider-server-in-azure/ but that wasn't a fully Azure VM image.

At Docker we have a close source set of Packer templates where we create and upload Azure VM images for eg. Windows Insider builds from ISO. So, it's possible to build something like this, but the repo isn't in a state to make it public.
