### ISSUE TITLE
vagrant user cannot connect via ssh

### ISSUE THREAD

**Issue by gitttt** [StefanScherer/packer-windows#260]
I did a `vagrant up` on the vagrant box 
`StefanScherer/windows_2019        (vmware_desktop, 2020.02.12)`
and installed the ssh server via `"Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"`

The server starts and works fine but the user `vagrant` cannot connect, neither from within the VM (ssh vagrant@127.0.0.1) nor from the outside. It says permission denied. I used vagrant as password, the same I use when I log into the VM.

I created another user and I am very well able to connect. So it has something to do with the user `vagrant`. Running Get-LocalUser showed no differences between user `vagrant` and my newly created user `asdf`

PS C:\Windows\system32> Get-LocalUser

```
Name               Enabled Description
----               ------- -----------
Administrator      True    Built-in account for administering the computer/domain
asdf               True
DefaultAccount     False   A user account managed by the system.
Guest              False   Built-in account for guest access to the computer/domain
sshd               True
vagrant            True    Vagrant User
WDAGUtilityAccount False   A user account managed and used by the system for Windows Defender Application Guard scen...
```
Both accounts are of type  `LocalUser`.
Why is it nor working for `vagrant`? What is so special about this account?

**Comment by gitttt** [comment]
I found the problem. It is [this bug][1] in openssh for Windows. The hostname (computername) must not be the same as the user name. Both were vagrant in my case.

You can fix it either by modifying your `Vagrantfile` and setting 
`config.vm.hostname` to a value different to `vagrant`. Alternatively, you can change your hostname from inside the VM, e.g. from Powershell via `Rename-Computer -NewName foo -Force -PassThru` (requires restart).

  [1]: https://github.com/PowerShell/Win32-OpenSSH/issues/1252

**Comment by StefanScherer** [comment]
Oh wow, that‘s a weird bug. Thanks @gitttt for sharing the workaround.
