### ISSUE TITLE
2020.04.15 Version not "currently released version" on vagrantup

### ISSUE THREAD

**Issue by juadde** [StefanScherer/packer-windows#266]
Hello,

I seems that when you didn't tell [vagrantup](https://app.vagrantup.com/StefanScherer/boxes/windows_2019) that 2020.04.15 is the good version when StefanScherer/windows_2019 is defined. It defaults to 2020.02.26.

Is this intended? Should we not use 2020.04.15 yet?

If not could you switch the currently released to 2020.04.15?

Thanks for your boxes!

**Comment by StefanScherer** [comment]
Hello @juadde,
Correct. I do not always build all variants of the boxes. Building the boxes costs me some money for the build machines. And I do not always have time to dig into CI problems. Last time I think hyperv is also missing due to a problem in my automation scripts.

**Comment by juadde** [comment]
OK, no problem, thanks for your answer!
