### ISSUE TITLE
Building QEMU images fail with recent Packer version

### ISSUE THREAD

**Issue by neanton** [StefanScherer/packer-windows#280]
In a recent version of Packers' QEMU builder there were changes how additional QEMU Args are handled.
Args override defaults set by Packer. Please see:
- https://www.packer.io/docs/builders/qemu#qemuargs
- https://github.com/hashicorp/packer/pull/10077

As per docs users should re-apply default `-drive` arguments. Currently Packer 1.6.5 starts QEMU without disk image provided through `iso_url` and VM boot hangs on `Booting from Floppy...` message.

Providing additional QEMU arg `-disk` with the correct ISO file resolves the problem, but I don't see a way how to pass an actually downloaded ISO on the filesystem to `-disk` argument.

Generally I think that overriding `-disk` args does not look good, but don't know how to properly load `virtio-win.iso`. Maybe an option would be to extract ISO image contents and pass files as `cd_files` https://www.packer.io/docs/builders/qemu#cd_files option.

Another idea is to extract ISO to an additional floppy folder.

**Comment by thejinx0r** [comment]
I have the same issue with packer v.1.6.5. Good thing it's documented version 1.6.0 is recommended.

**Comment by StefanScherer** [comment]
There are two pull requests #281 and #282 that may fix the issue. I don‘t have the bandwidth to test these, but maybe together we find the correct solution. 😀

**Comment by StefanScherer** [comment]
I've merged the two pull requests. Hope that helps.
