### ISSUE TITLE
virtio drivers?

### ISSUE THREAD

**Issue by malikumaliku** [StefanScherer/packer-windows#284]
Hello,

Are virtio drivers installed for the windows server 2019 image?
I am using the vagrant box.

As per the ticket https://github.com/StefanScherer/packer-windows/pull/216
it seems that something was done.

But I use vagrant mutate to transform into libvirt and the boot fails.
If I override the vagrant definition to use ide instead of virtio the image can boot properly.

**Comment by StefanScherer** [comment]
Maybe @qmfrederik knows more details?

But if you try to convert the virtualbox/vmware boxes then there is no virtio driver installed.

**Comment by qmfrederik** [comment]
Yes, like the README says, if you download the virtio iso and then run e.g. `packer build --only=qemu --var virtio_win_iso=./virtio-win.iso ./windows_2019_docker.json`, you'll end up with a box with the virtio drivers embedded.

The virtio drivers won't be embedded if you build for another virtualization platform, so coverting VirtualBox -> KVM won't work.
