### ISSUE TITLE
The windows_10 (virtualbox, 2020.11.18) license will expire soon

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#285]
Friendly reminder the windows_10 (virtualbox, 2020.11.18) license will expire soon.

<img width="431" alt="chocolatey_test_environment_windows_10__Running_" src="https://user-images.githubusercontent.com/6723257/106367820-0aaf9000-630b-11eb-9587-e8b180a7cd34.png">

**Comment by StefanScherer** [comment]
Thanks for the heads-up. I already tried to rebuild, but the pipeline has issues https://app.circleci.com/pipelines/github/StefanScherer/packer-builder/314/workflows/a4b1fbb0-a382-4eed-9e2f-1418174ae176/jobs/1574 and I hadn't the time to look and fix it.

**Comment by StefanScherer** [comment]
- Searched for the error "vmware-iso: Error starting VM: VMware error: Error: The operation was canceled" and found your bug report https://github.com/hashicorp/packer/issues/5754 :-) I had pinned version of Packer 1.5.1 and VMware Workstation 14.1.7 in the past, so I guess the underlying Ubuntu or the baremetal machines at Equinix have changed. 🤔 

- Tried to update to VMware Workstation 14.1.8 and Packer 1.6.6, but ran into a different problem. Maybe there is no 14.1.8 for Linux.

Manually installed VMware Workstation 16.1.0 on that machine, but ran into https://github.com/hashicorp/packer/issues/10009

- Updated to VMware Workstation 15.5.7, but then I get  "vmware-iso: Error starting VM: VMware error: Error: The operation was canceled" again. 😢 

Giving up for now as the machines cost money per hour. I don't see a quick fix for my pipeline. 🐼

**Comment by StefanScherer** [comment]
Tried a few more things on Equinix, updated to Ubuntu 20.04, used bigger machines there, but still the "The operation was canceled" error. 😢

**Comment by woa7dklb** [comment]
@StefanScherer 
via the link https://app.circleci.com/pipelines/github/StefanScherer/packer-builder/314/workflows/a4b1fbb0-a382-4eed-9e2f-1418174ae176/jobs/1574
i see the job is run as: "Executor: Docker Medium: 2 CPU / 4 GB RAM"
i bet 4GB RAM is to less or?

**Comment by StefanScherer** [comment]
@woa7dklb No worries. This is just the CircleCI worker. On that I install terraform and the packet CLI to spin up a baremetal machine at Equinox (formerly packet) and do the packer build there. 
CircleCI is just here for the logs 🙂

**Comment by woa7dklb** [comment]
ah, ok and if you run the terraform and the packet CLI directly,
the problem is the same?

**Comment by StefanScherer** [comment]
The provisioning is not the problem. I logged into the equinix machine to investigate, and I get the same VMware error when running the packer build command.
In the past it was because I chose a too small machine that has a smaller CPU with less capabilities. But I now tried the even more expensive machines. I have no clue and even the vmware logs under the hood don't tell me much more. 😕

**Comment by woa7dklb** [comment]
can you post me the direct build command? than i will try it also

**Comment by StefanScherer** [comment]
Depending on the hypervisor you  want to use you can run a packer build with

```
packer build --only=virtualbox-iso windows_10.json
packer build --only=vmware-iso windows_10.json
packer build --only=hyperv-iso windows_10.json
```

**Comment by basictheprogram** [comment]
I normally (packer) build on a ubuntu linux computer. In an attempt to add more knowledge to this problem I spun up an old iMac with a brew installed toolchain. I am surprised the vagrant build worked!
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G14042
```
```
$ packer --version
1.6.6
```
```
$ brew info virtualbox
virtualbox: 6.1.18,142142
https://www.virtualbox.org/
/usr/local/Caskroom/virtualbox/6.1.18,142142 (3 files, 119MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/virtualbox.rb
```

**Comment by StefanScherer** [comment]
Thanks  @basictheprogram , virtualbox is not the problem.  The packer build for virtualbox seems to work on the Equinix machine, but VMware Workstation is failing to start the VM. I personally use VMware so that's a blocker for me to pay for cloud machines that run my packer builds.
Maybe I find some more time to find out what's causing the issue, but without a VMware my setup is rather useless for my use cases.

For virtualbox you can find other VM's on vagrant cloud, eg. this https://app.vagrantup.com/gusztavvargadr/boxes/windows-10 . @gusztavvargadr does a fantastic work to provide several different Windows machines and keeps them up to date. I only  can recommend his vagrant boxes.

**Comment by atwright147** [comment]
Should `packer build --only=parallels-iso windows_10.json` work?

**Comment by basictheprogram** [comment]
Thanks for the recommendation for  @gusztavvargadr virtualboxes. 

Is there the possibility that you can change the build workflow to exclude the vmware build? 

I have a ESXi node spinning up and I'll do some testing.

**Comment by StefanScherer** [comment]
@basictheprogram Well, I could skip the VMware build, but that doesn't make sense for me 😅 
I spent a couple of hours this morning to investigate the problem in a local nested VMware box and I think I found a fix.
Current build is running https://app.circleci.com/pipelines/github/StefanScherer/packer-builder/345/workflows/99980120-7fc6-4ce0-80ba-cb030f1d04bc/jobs/1606

**Comment by StefanScherer** [comment]
And there are new 📦 🎉
