### ISSUE TITLE
Question - change disk size dynamically for vagrant machine

### ISSUE THREAD

**Issue by zili55** [StefanScherer/packer-windows#305]
Hello! I see that disk size is fixed for 60GB e.g on [line](https://github.com/StefanScherer/packer-windows/blob/03fa44aa74f8547b2d70adfe90b28b944ccf8734/windows_2019.json#L183). I started using `StefanScherer/windows_2019` (btw thanks for that, nice box). 

It is possible to somehow change disk size from Vagrantfile or provision scripts? For example I would like to start new vagrant machine via `StefanScherer/windows_2019` but with 100GB disk. It is possible to somehow currently or I need to edit that json, and make a new vagrant box?

Thanks in advance!

**Comment by StefanScherer** [comment]
Hi @zili55 Thanks that you find the boxes useful 😊

I haven‘t used resizing existing VirtualBox or VMware disks, maybe this experimental feature could help https://www.vagrantup.com/docs/disks/usage

**Comment by zili55** [comment]
okey, thanks for your answer, when I will have time I try it :)
