### ISSUE TITLE
Sysprep Windows 2016 Server?

### ISSUE THREAD

**Issue by SharePointOscar** [StefanScherer/packer-windows#32]
Howdy Stefan, wondering if the sysprep command on the readme file works for you when you try it on the windows_2016.json template?  Keeps timing out for me for some odd reason..

**Comment by StefanScherer** [comment]
Haven't tried with sysprep for a while.

**Comment by rgl** [comment]
I have no clue about this flavor of the sysprep invocation, but if you are using Vagrant, you might want to do a sysprep as a provision step with the [vagrant-windows-sysprep](https://github.com/rgl/vagrant-windows-sysprep) plugin, which I'm using at [windows-domain-controller-vagrant](https://github.com/rgl/windows-domain-controller-vagrant). The downside... the sysprep is not done in the base box.

**Comment by SharePointOscar** [comment]
Awesome Rui I'll try that :)

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by StefanScherer** [comment]
I can reproduce the problem. It seems that `c:/windows/system32/sysprep/sysprep.exe /oobe /generalize /shutdown /mode:vm` is a better way to generalize the VM, this works and the Win 2016 VM shuts down.
We also no longer need an `unattend.xml`.
Found that here: https://www.thomasmaurer.ch/2016/05/windows-sysprep-for-virtual-machines/

**Comment by StefanScherer** [comment]
Oh no, this generates a base box with interactive OOBE.

**Comment by StefanScherer** [comment]
Sysprep couldn't remove files and aborted the shutdown due to an additional service running. I've updated the `windows_2016.json` with a working `sysprep.bat` in commit d3cf867d841947a3382a884f382aa540d6795bd2.

**Comment by SharePointOscar** [comment]
Thank you @StefanScherer  I will pull your changes in to my branch and give it a shot!  You the man!
