### ISSUE TITLE
Windows 10 December 2022 updates break the enable-winrm.ps1 script

### ISSUE THREAD

**Issue by corbob** [StefanScherer/packer-windows#322]
This line: https://github.com/StefanScherer/packer-windows/blob/02c28376379d68d7e03f0056cfedd241e93879b3/scripts/enable-winrm.ps1#L2 no longer returns an actionable object.

Left is from a system before the December updates were applied, and right is after they're applied.

![image](https://user-images.githubusercontent.com/30301021/207704660-5bffc5d1-720a-44e6-95a7-bf2eb41f4945.png)

**Comment by corbob** [comment]
Ok, for my setup, I was able to remove the first 3 lines:

https://github.com/StefanScherer/packer-windows/blob/02c28376379d68d7e03f0056cfedd241e93879b3/scripts/enable-winrm.ps1#L1-L3

And replace them with one line:

```powershell
Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
```

However, I have no idea if this works with Server Operating Systems, or with anything other than Windows 10 22H2.

**Comment by javajase** [comment]
I can confirm the same issue and fix is required in Windows 11 22H2, thank you for sharing

**Comment by ccraluca** [comment]
Hi @corbob, 
I tried your solution but it didn't work. Could this error be related to the same update?
I couldn't find a fix and this came out without making any changes to the code.
![image](https://user-images.githubusercontent.com/82503380/211781822-b1b83974-b1bf-441d-9c8e-d16337d2ce3f.png)

**Comment by sva-mk** [comment]
I can confirm that the issue is still present on 21H2.
For me, the fix from corbob solved the problems!
Thanks for sharing your work!

> Ok, for my setup, I was able to remove the first 3 lines:
> 
> https://github.com/StefanScherer/packer-windows/blob/02c28376379d68d7e03f0056cfedd241e93879b3/scripts/enable-winrm.ps1#L1-L3
> 
> And replace them with one line:
> 
> ```powershell
> Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
> ```
> 
> However, I have no idea if this works with Server Operating Systems, or with anything other than Windows 10 22H2.

**Comment by imincik** [comment]
I confirm the issue while running `packer build --only=virtualbox-iso ./windows_10.json`. And I also confirm that patch from @corbob fixed the problem. Thank you @corbob .

**Comment by StefanScherer** [comment]
Do we have any confirmation if this change works on Windows Server OS?
I moved away from Intel MBP, so I can't test locally.
