### ISSUE TITLE
windows_10.json gets stuck on install screen

### ISSUE THREAD

**Issue by synick** [StefanScherer/packer-windows#43]
I am trying to work it out, but when I run the build_windows10.ps1, it gets stuck on the first screen. Where the user selects the language. If you just click continue, the rest of it runs fine. 

You having this issue? Thinking of putting in some keystrokes in there, such as "< enter >"

**Comment by StefanScherer** [comment]
This got fixed in the Autounattend.xml with https://github.com/StefanScherer/packer-windows/commit/dbe0e43660cf156a1b9097d4874d5687591897e1#diff-49fb16cd415b7309be7bed04a3d50fc8 for the newer ISO files. 
I‘ll rerun a build to check.

**Comment by StefanScherer** [comment]
Which ISO file do you use?

**Comment by synick** [comment]
That worked for me, was using the '15063.0.170317-1834.RS2_RELEASE_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO' image. Same thats used in the windows_10.json file. Thank you.
