### ISSUE TITLE
packer build hangs: Shutdown Event Tracker popup

### ISSUE THREAD

**Issue by StefanScherer** [StefanScherer/packer-windows#45]
During the win-updates.ps1 script Windows Server 2016 (after the CU in October 2017?) the VM hangs with an popup "Shutdown Event Tracker".

<img width="1027" alt="bildschirmfoto 2017-10-13 um 06 33 45" src="https://user-images.githubusercontent.com/207759/31530424-addf793e-afe0-11e7-8539-c633befd74d1.png">

I tried that twice.

The win-updates.ps1 script started

<img width="502" alt="bildschirmfoto 2017-10-13 um 06 40 46" src="https://user-images.githubusercontent.com/207759/31530937-0de4a18a-afe4-11e7-9d8a-823dc731978e.png">

The machine crashed

<img width="1136" alt="bildschirmfoto 2017-10-13 um 06 44 38" src="https://user-images.githubusercontent.com/207759/31530943-12369ffe-afe4-11e7-9ccc-dbbcd2233e82.png">

**Comment by beutepa** [comment]
Same issue building on Windows 10 (Version 1607 - OS Build 14393.1715), using packer 1.0.0

It cloned the 'my' branch yesterday and ran:
```
packer build --only=hyperv-iso windows_2016_docker.json
```
With the same result.

**Comment by beutepa** [comment]
I don't have the issue when using another Windows Server 2016 ISO on the same system:
```
Windows Server 2016 (x64) - DVD (English)
Released: 1/12/2017
File name: en_windows_server_2016_x64_dvd_9718492.iso
```

**Comment by StefanScherer** [comment]
This turns out to be a problem with macOS High Sierra's new filesystem APFS and VMware Fusion 8.5.8 or 10.0.1 with growable disks. I've opened an issue at VMware Support and they can reproduce the problem.

Workaround right now is to switch to a preallocated disk:

```
packer build \
  --only=vmware-iso \
  --var disk_type_id=3 \
  --var disk_size=30720 \
  windows_2016_docker.json
```

**Comment by StefanScherer** [comment]
https://communities.vmware.com/message/2714255#2714255 and 
VMware Support Request 17606390010
