### ISSUE TITLE
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 4294967295

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#51]
I worked around #49 now hitting another problem.

```shell
virtualbox-iso: 1>    Compiling assembly TaskScheduler, Version=10.0.0.0, Culture=Neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil (CLR v4.0.30319) ...
    virtualbox-iso: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 4294967295

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 4294967295
```

**Comment by StefanScherer** [comment]
Is it repeatable? I got it once, later on it worked.
Maybe we should skip this the script if it's not running well.

**Comment by basictheprogram** [comment]
Oddly, 1 packer build system, happens every time. Testing our other packer build system. I'll report back here when the build it complete.

**Comment by StefanScherer** [comment]
Thanks for testing again. I'll do some tests here, can repro and see how to fix it.

**Comment by StefanScherer** [comment]
I've updated the windows_10 template and removed the provision script. I can reproduce the problem, I've tested with the Win10Eval ISO.

**Comment by basictheprogram** [comment]
Sorry it took so long. My other packer build system is my old laptop and is very slow. I can duplicate the issue on this system as well. Just adding this comment.
