### ISSUE TITLE
Error during build?

### ISSUE THREAD

**Issue by dky** [StefanScherer/packer-windows#6]
Hello, I'm receiving the following error on build? Any tips on what to look at? 

Thanks 

==> vmware-iso: Provisioning with shell script: ./scripts/docker/patch-boot-time-for-containers.ps1
    vmware-iso: Running windowsservercore once and tagging it as latest
    vmware-iso: C:\Windows\system32\docker.exe: Error parsing reference: "windowsservercore:" is not a valid repository/tag.
    vmware-iso: See 'C:\Windows\system32\docker.exe run --help'.
    vmware-iso: C:\Windows\system32\docker.exe: "commit" requires a minimum of 1 argument.
    vmware-iso: See 'C:\Windows\system32\docker.exe commit --help'.
    vmware-iso:
    vmware-iso: Usage:	docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]
    vmware-iso:
    vmware-iso: Create a new image from a container's changes
    vmware-iso: C:\Windows\system32\docker.exe: "tag" requires 2 arguments.
    vmware-iso: See 'C:\Windows\system32\docker.exe tag --help'.
    vmware-iso:
    vmware-iso: Usage:	docker tag [OPTIONS] IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]
    vmware-iso:
    vmware-iso: Tag an image into a repository
    vmware-iso: C:\Windows\system32\docker.exe: "rm" requires a minimum of 1 argument.
    vmware-iso: See 'C:\Windows\system32\docker.exe rm --help'.
    vmware-iso:
    vmware-iso: Usage:	docker rm [OPTIONS] CONTAINER [CONTAINER...]
    vmware-iso:
    vmware-iso: Remove one or more containers
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by StefanScherer** [comment]
@dky The patch script runs after docker and the base images should be installed. It seems that the windowsservercore base image wasn't installed. Maybe the download dropped and the previous script didn't abort so the error occurs in this script.
Just try again to build the VM.
I've created both VMware and VirtualBox yesterday and it did work for both.

**Comment by dky** [comment]
@StefanScherer Thanks, That must have been it, I was on a bad cellular connection during the download and it must have dropped. Re-trying it right now on a better connection and it's going... At the defrag stage so finger crossed it will wrap up soon.
