### ISSUE TITLE
windows_2016_docker.json: unknown configuration key: "vmx_remove_ethernet_interfaces"

### ISSUE THREAD

**Issue by TheBigBear** [StefanScherer/packer-windows#60]
the key ```vmx_remove_ethernet_interfaces``` needs to be in the ```vmx_data``` section
else it will say:
```
1 error(s) occurred:

* unknown configuration key: "vmx_remove_ethernet_interfaces"
```

if I move it into the ```vmx_data``` section the error goes away

```
diff --git a/windows_2016_docker.json b/windows_2016_docker.json
index 1a70bd5..d23badb 100644
--- a/windows_2016_docker.json
+++ b/windows_2016_docker.json
@@ -57,14 +57,14 @@
         "./scripts/microsoft-updates.bat",
         "./scripts/win-updates.ps1"
       ],
-      "vmx_remove_ethernet_interfaces": true,
       "vmx_data": {
         "RemoteDisplay.vnc.enabled": "false",
         "RemoteDisplay.vnc.port": "5900",
         "memsize": "2048",
         "numvcpus": "2",
         "scsi0.virtualDev": "lsisas1068",
-        "vhv.enable": "{{user `vhv_enable`}}"
+        "vhv.enable": "{{user `vhv_enable`}}",
+        "vmx_remove_ethernet_interfaces": true
       }
     },
     {
```

**Comment by StefanScherer** [comment]
Thanks for investigating the templates.
I don't know why this shows an error.
I've validated it on a Mac with
```
$ packer validate --only vmware-iso windows_2016_docker.json 
Template validated successfully.
```

The keyword `vmx_remove_ethernet_interfaces` (https://www.packer.io/docs/builders/vmware-iso.html#vmx_remove_ethernet_interfaces) should be in the vmware-iso section. The vmx_data section is to put additional vmx settings into the *.vmx file.

It still seems to me you're running an older version of packer. Maybe you still have some outdated external plugins somewhere? Packer was a single binary, then they extracted all plugins into tons of extra binaries, now Packer is a single binary again.

**Comment by TheBigBear** [comment]
this and a couple other bugs all seem to be inconsistencies between windows and mac os x and mac os x brew binaries of packer.
Will report these findings upstream. 

Sorry to have pointed at your 'innocent' json files.

same is true for https://github.com/StefanScherer/windows-docker-machine/issues/14#issuecomment-348717122
