### ISSUE TITLE
vmware-iso builder (hardware) version:11 vs VMware Fusion 8 (and higher) Workstation 11 (and higher)

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#68]
I use VMware Fusion 8, Fusion 10, Workstation 12, Workstation 14 for generating my packer images. All of the above release complain about the hardware compatibility version number and request I upgrade it.

https://kb.vmware.com/s/article/1010675
https://kb.vmware.com/s/article/1014006

VMware Fusion 7.x, hardware version 11, 
Latest maintenance release 7.1.3, Nov 12, 2015, newest operating system OS X El Capitan (10.11)

VMware Workstation 11.x, hardware version 11,
Latest maintenance release 11.1.2, Jun 15, 2016, newest operating system Windows 10

Can we increment the version to at least 12?

I'll make a PR if this is approved.

**Comment by StefanScherer** [comment]
That sounds reasonable to upgrade to version 12. 
version 11 was needed to make Hyper-V work in Server 2016 / 10.
