### ISSUE TITLE
Bad ISO checksum for 1709

### ISSUE THREAD

**Issue by bkleef** [StefanScherer/packer-windows#75]
```
➜  packer-windows git:(my) git rev-parse --short HEAD
c95fc93
```
```
➜  packer-windows git:(my) packer build --only=virtualbox-iso windows_server_1709_docker.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: https://software-download.microsoft.com/pr/en_windows_server_version_1709_x64_dvd_100090904.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: ca1108d5be2c091bfb57e8f3db3be1e8baa9c32802131f7a6e43e63f7b596591
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
```

**Comment by StefanScherer** [comment]
Oh, the iso_url cannot be used directly. Please have a look at the second link in the json file. You need a MSDN subscription to have access to the ISO and download it manually. I just add the link so people can compare the file name of the ISO file.

https://github.com/StefanScherer/packer-windows/blob/c95fc93b727d8cd986db5e0dc899b4347538ce00/windows_server_1709_docker.json#L181-L182

Probably it's easier to try the latest things with the Windows Insider Server Preview which you can easily join and have access to also manually downloadable Insider ISO files.
