### ISSUE TITLE
instal-docker.ps1 failed

### ISSUE THREAD

**Issue by mwieczorek** [StefanScherer/packer-windows#8]
host: win8.1
packer v 0.10.1
virtualbox 5.0.20

I run:
```packer.exe build -only=virtualbox-iso windows_2016_docker.json```
And after some time got error (whole log in [gist](https://gist.github.com/mwieczorek/47c865787d92de35a004469eabbad83e) )
```
2016/05/14 22:08:01 packer.exe: 2016/05/14 22:08:01 [INFO] command 'set "PACKER_BUILDER_TYPE=virtualbox-iso" && set "PA
CKER_BUILD_NAME=virtualbox-iso" &&  cmd /c "c:/Windows/Temp/script.bat"' exited with code: 1
```
I wanted to check what's wrong in the script so I removed powershell provisioner with the ./scripts/docker/install-docker.ps1, and build box.

And then I started the VM, and run script manually. During the script I saw some 'permission' problems.
![image](https://cloud.githubusercontent.com/assets/7051680/15270479/35e6a2ae-1a22-11e6-93c8-af49239756a0.png)
That's strange, because vagrant user is in Administrators group, and scheduled task is run as vagrant.
So I 'googled' and found:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa383085(v=vs.85).aspx

> If a task is registered using the Administrators group for the security context of the task, then you must also set the RunLevel property to "**HighestAvailable**" to run the task.

But in the install-docker.ps1:
```xml
<Principals>
    <Principal id="Author">
      <UserId>vagrant</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
```
When I changed that to HighestAvailable - error was gone.

Did you have such problem? Maybe I'm doing something else wrong?

If not - maybe we can change that to HighestAvailable? I can make a PR.

**Comment by StefanScherer** [comment]
@mwieczorek No I didn't have such problem building the boxes for VMware and VirtualBox. Strange.
But your investigation looks very good. So please send a PR :-)

**Comment by mwieczorek** [comment]
@StefanScherer 
Ok.
Give me a few days - I want to check something else also.
Thanks,
M.

**Comment by mwieczorek** [comment]
My investigation was not so good :-)
Short story: no PR is needed.
Long story:
I had problems during running install-docker.ps1. So I build box without it (and all next scripts), logged into and tried to run it manually. And I saw those 'permissions errors'. But I think it occurs only when I run it on the system, and not by winrm communicator. 
The problem is somewhere else.
So let's close this issue.

**Comment by StefanScherer** [comment]
@mwieczorek You might be interested in my latest change https://github.com/StefanScherer/packer-windows/blob/my/scripts/docker/install-docker.ps1 removing the scheduled task und just using `docker pull` to install the base OS images.

**Comment by mwieczorek** [comment]
@StefanScherer Thanks.
I'll try it this or next week. I will let you know if I encounter any problems.
