### ISSUE TITLE
vmware-iso builds + thin disks vs scripts/compact.bat

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#80]
Discussing this over on the [Packer Google Group](https://groups.google.com/d/msg/packer-tool/fYWskajreds/eM-v25JfBgAJ).

Creating a VMware image with 756GB disk, allocated thin. Everything looks correct until the script/compact.bat runs in the provisioners.

Looks like SDelete causes the thin disk to provision all 756G of disk.

Looking at script/compact.bat I see it's skipped for hyperv.
```bat
if "%PACKER_BUILDER_TYPE:~0,6%"=="hyperv" (
  echo "Skip compact steps in Hyper-V build."
  goto :eof
)
```
I'm not sure of the ramifications of this change so I'm opening an issue for discussion.

Thanks.

**Comment by StefanScherer** [comment]
Well it usually saved 1-2 GByte of the resulting *.box file when running all the steps in compact.bat
In the meantime we have linked clone support so the 1-2 GB would only need extra space once. But people have to download more. See eg. https://app.vagrantup.com/StefanScherer/boxes/windows_2016_docker/versions/2017.12.14

You could remove the compact step completely and see how it goes.

**Comment by basictheprogram** [comment]
I might be wrong where the provisioning of the disk increases.

-or-

the vsphere post-processor coverts(?) the thin provisioning to thick?

```shell
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
  <snip>
==> vmware-iso: Waiting for WinRM to become available...
```
vmdk size at this poing
```shell
output-vmware-iso$ ls -lha
<snip>
-rw-------   1 tanner  staff    20G Jan 28 22:20 disk.vmdk
```
The start of apply windows updates
```shell
output-vmware-iso$ ls -lah *.vmdk
-rw-------  1 tanner  staff    20G Jan 28 22:33 disk.vmdk
```
After windows updates
```shell
output-vmware-iso$ ls -alh *.vmdk
-rw-------  1 tanner  staff    23G Jan 28 23:48 disk.vmdk
```
After all the provisioning scripts run
```shell
output-vmware-iso$ ls -alh *.vmdk
-rw-------  1 tanner  staff    23G Jan 29 00:04 disk.vmdk
```
before compacting
```shell
output-vmware-iso$ ls -alh *.vmdk
-rw-------  1 tanner  staff    23G Jan 29 00:06 disk.vmdk
```
Now trying to upload with the vsphere and it's failing
```shell
==> vmware-iso: Cleaning VMX prior to finishing up...
    vmware-iso: Unmounting floppy from VMX...
    vmware-iso: Detaching ISO from CD-ROM device...
    vmware-iso: Disabling VNC server...
    vmware-iso: Removing Ethernet Interfaces...
==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi and the format needs to be specified)...
==> vmware-iso: Running post-processor: vsphere
    vmware-iso (vsphere): Uploading output-vmware-iso/WindowsServer2016.vmx to vSphere
Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Opening VMX source: output-vmware-iso/WindowsServer2016.vmx
Opening VI target: vi://XXXX
Error:
 - Insufficient disk space on datastore 'esx-3-local'.
Completed with errors
```
There's enough disk space on esx-3-local  to hold 23G but not 756G specified for the C: drive on WindowsServer2016 VM.

**Comment by StefanScherer** [comment]
The default `disk_mode` is "thick": https://www.packer.io/docs/post-processors/vsphere.html

**Comment by basictheprogram** [comment]
```shell
packer build -only=vmware-iso -var 'disk_size=786432' -var 'disk_type_id=0' -force -on-error=ask windows_2016.json
```

**Comment by StefanScherer** [comment]
The `disk_type_id` is for the VMware Fusion/Workstation build. 
I have seen that you use a vSphere post processor. This has another option `disk_mode`, that seem to be your problem during the upload.

**Comment by basictheprogram** [comment]
I think this is a packer/post-processor problem not a packer-window problems.

```json
    {
        "keep_input_artifact": true,
        "type" : "vsphere",
        "cluster" : "XXXX",
        "datacenter" : "XXXX",
        "datastore" : "esx-3-local",
        "host" : "XXXX",
        "password" : "XXXX",
        "username" : "XXXXXl",
        "vm_name" : "Windows2016-post-processor",
        "vm_network" : "XXXX",
        "insecure" : "true",
        "disk_mode" : "thin",
        "only": ["vmware-iso"]
    }
```

**Comment by basictheprogram** [comment]
Doing both disk_type_id and disk_mode on a Windows packer system "does the right thing".  The problem is either on macOS packer or a "personal problem" with my setup on macOS.

I'm going to close this ticket.
