### ISSUE TITLE
Build  errored: Timeout while waiting for machine to shut down

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#89]
I'm trying to use a volume license .iso of Windows Server 2016 and packer is throwing an error: "Build  errored: Timeout while waiting for machine to shut down". The only thing I changed is the name and location of the .iso image.

I'm trying to use file:///Users/tanner/Downloads/SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.ISO and not the 180 days licensed image.

I assume the volume licensed Windows Server 2016 images should work with packer? 

Snipped from the logs:
```
==> vmware-iso: Gracefully halting virtual machine..
==> vmware-iso: Timeout while waiting for machine to shut down
==> vmware-iso: Stopping virtual machine..
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout while waiting for machine to shut down.
```
[packer.log](https://github.com/StefanScherer/packer-windows/files/1804910/packer.log)

Changed the restart_timeout
```
    "restart_timeout": "1h",
```
Does not change things.

**Comment by StefanScherer** [comment]
I sometimes build with a MSDN ISO file and it worked for me.
Maybe we can see more with `PACKER_LOG` variable set to eg. `1`.
Do you run a different shutdown command?

**Comment by basictheprogram** [comment]
Thought I did the build with PACKER_LOG=1, I'll run it again.

Only change from upstream is changing iso_url to SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.ISO

**Comment by basictheprogram** [comment]
At a loss on what is wrong here. Did some debugging. Installed a pause into the sysprep.bat so I could try a few things by hand.
```batch
net stop tiledatamodelsvc
pause
c:\windows\system32\sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:a:\unattend.xml
```
Packer log snippet
```shell
2018/03/26 00:03:21 packer: The Tile Data model server service is stopping.
2018/03/26 00:03:21 packer: The Tile Data model server service was stopped successfully.
2018/03/26 00:03:21 packer:
2018/03/26 00:03:21 packer:
2018/03/26 00:03:21 packer: C:\Users\vagrant>pause
2018/03/26 00:03:21 packer: Press any key to continue . . .
```
I went to the VM, fired up an Administrator powershell and executed
```powershell
c:\windows\system32\sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:a:\unattend.xml
```
And the VM shutdown, Pressed any key to continue and packer **still** threw an error.
```shell
2018/03/26 00:03:21 packer: 2018/03/26 00:03:21 Shutdown stderr:
2018/03/26 00:03:21 ui error: ==> vmware-iso: Timeout while waiting for machine to shut down.
==> vmware-iso: Timeout while waiting for machine to shut down.
```
Note the timestamp on the Shutdown stderr:, it's like packer isn't wait any amount of time for shutdown to happen.
