### ISSUE TITLE
Issues during 7zip download on hyperv

### ISSUE THREAD

**Issue by eeevans** [StefanScherer/packer-windows#94]
Trying to build the Windows 2019 with hyperv, I was getting messages about the connection being forceably closed and the file would not be there run install.  I added ' | out-null' inside the " at the end of the second line in vm-guest-tools.bat and that got me past the issue.  It successfully created the box after that.  It may have just been a local network issue and coincidence that it started working after the change. 
 Hope this helps someone.

**Comment by StefanScherer** [comment]
Thanks @eeevans. 
I haven't tried hyperv yet with the 2019 template, only VMware.
Let's see what others report.

**Comment by StefanScherer** [comment]
Started a test build https://circleci.com/gh/StefanScherer/packer-builder/206
Let's see how it works

**Comment by StefanScherer** [comment]
Closing, the latest packer templates work for hyperv builder.
