### ISSUE TITLE
Error compacting disk: VMware error:

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#97]
Starting getting this error after after 5bc3cf59fb8db001b3bcb1e1d9fe7379b8e3c083 but git blame shows nothing changed regarding windows_10.json and this used to work. 

What's changed is I applied:
  * macOS High Sierra 10.13.4 Update
  * Comand Line Tools (macOS High Sierra version 10.13) for Xcode

$ packer build -only=vmware-iso -var 'disk_size=65536' --force  windows_10.json
```
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error compacting disk: VMware error: Failed to open the disk '/Users/tanner/projects/packer/Stefan-Schere-packer-windows/output-vmware-iso/disk.vmdk' : The specified virtual disk needs repair (0x3e86).
Failed to defragment: The specified virtual disk needs repair (0x3e86).

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error compacting disk: VMware error: Failed to open the disk '/Users/tanner/projects/packer/Stefan-Schere-packer-windows/output-vmware-iso/disk.vmdk' : The specified virtual disk needs repair (0x3e86).
Failed to defragment: The specified virtual disk needs repair (0x3e86).
```

**Comment by StefanScherer** [comment]
Looks more like a VMware problem.

**Comment by StefanScherer** [comment]
Does this still happen?

**Comment by StefanScherer** [comment]
I run VMware builds on packet.net machines and could not find a problem. So I don't think it's a problem in the templates.
